language: ruby
rvm:
  - 2.2.2
  - ruby-head
before_script:
  - psql -c 'create database enlighten_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
