# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 229f774384faafa2c6c8240d8c10ee629c70540e568a6865d942a745352a9a2d845a13a6846df1f690c4476c5bab57984102530352628c665c84b311246a6d3c

test:
  secret_key_base: e9a3a8af036f00176b4cd674aa003169c0411e8866669827764c84b6b0171496d42b037cfa99db6c112b1c3a950a0a8bb55df1a246434da50e1d8786e2480365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
